### ISSUE TITLE
npm installed another grunt-svg2png

### ISSUE THREAD

**Issue by xth2b** [pascalduez/grunt-svg2png#1]
With `npm install --save-dev grunt-svg2png`, I got `https://www.npmjs.com/package/grunt-svg2png` (https://github.com/dbushell/grunt-svg2png) installed, instead of this repository.

How can I install this one from npm? Thanks!

**Comment by pascalduez** [comment]
Hello,

as [stated in the Readme](https://github.com/pascalduez/grunt-svg2png#motivation) this package is not published on npm, to avoid name conflicts and cluttering.

You can install it from Github: `npm i pascalduez/grunt-svg2png -D`

**Comment by xth2b** [comment]
Shame on me.  Thanks.

**Comment by pascalduez** [comment]
> Shame on me. Thanks.

No worry, also the Readme install instruction was wrong, I corrected it ;-)
